### ISSUE TITLE
Lỗi USB

### ISSUE THREAD

**Issue by ThiTraThanh** [ThiTraThanh/-3-Claw_data#1]
![z4623543463484_2dd7da330b4fb739f729368b4f1dd7ef](https://github.com/ThiTraThanh/-3-Claw_data/assets/132273033/dd3a7585-7a7a-408f-9fba-bb44db904c36)

**Comment by QuachNgoc** [comment]
Cập nhật Webdriver lên 116: https://googlechromelabs.github.io/chrome-for-testing/?fbclid=IwAR1eUyfQjjw9LCmBSnTfa7sB09KDmtlhidLXuQJzaev0mtW34rwVStQ5E34
